### ISSUE TITLE
File Follower: start and poll if watched directory does not exist

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#1004]
## What is the feature to be added?

The file follower ingesters currently refuse to start if watched directories do not exist, this makes it difficult to watch for data if a complete directory may come and go.

Currently this can be fixed using recursive mode, but depending on the location that may not be viable either.

We need to updates to the ingester (potentially guarded by a flag).

1. Ingest/watched directory stanzas should allow for some flag that tells the ingester "this directory may or may not exist"
2. Ingester (if allowed) should be allowed to start and if the directory does not exist, we kick off a routine that just periodically polls to see if the directory has shown up.
3. When a directory shows up, do the notification bind and continue as normal
4. If the directory is removed, remove the watcher and go back into a polling mode looking for the folder to show back up

## Why should we add this feature? (Business justification? What problem is the feature trying to solve?)

Sometimes its useful to watch for files showing up where the parent directory is transient too.

Recursive watches wont' work if say your target is `C:\stuff\` because then we would attempt to watch the root and all hell breaks loose.

## How does this feature address the above problem?

Allows for users to declare that a watched folder may or may not exist.

## Any other comments?

We may think about making this the default instead of a flag.  This has to be carefully balanced otherwise botched configs and or typos mean that the ingester comes up and does nothing and that will confuse the users even more.

**Comment by mike-wade-gravwell** [comment]
+1 Dan from P*. Claims he has a couple instances that are failing to start.

**Comment by kris-watts-gravwell** [comment]
there are a ton of issues around this:

1. what happens if a user typos?  is it ok to start and just not eat?
2. do we force them to set a flag saying its ok to start if a folder does not exist.
3. if you delete a watched directory, do we grab that watched directory and kick it into this "polling" mode and rewatch if it comes back?
4. what do we do if its created and we don't have permissions?  Ignore and keep polling?  bark and stop?

**Comment by mike-wade-gravwell** [comment]
1. what happens if a user typos? is it ok to start and just not eat?

I think so. I think it would be better to see in the gui that its connected and not sending data than for an admin to have to go hunt for the reason its not reporting. It might also be nice for the ingester to report an event into the gravwell tag that the folder is not present when it started up.

2. do we force them to set a flag saying its ok to start if a folder does not exist.

I think it should start either way. I think the admin should be able to diagnose as many issues as possible from gravwell.

3. if you delete a watched directory, do we grab that watched directory and kick it into this "polling" mode and rewatch if it comes back?

Yes. It might be nice to have a configuration option to allow the user to set the polling interval for missing directories

4. what do we do if its created and we don't have permissions? Ignore and keep polling? bark and stop?

I think it should send a message to the gravwell tag that it doesn't have permissions and repeat the message on whatever the polling interval is for missing directories.

**Comment by david-fritz-gravwell** [comment]
LGTM
