### ISSUE TITLE
Client: client does not detect that you are not logged on on calls

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#473]
### What are the steps to reproduce this issue?

run this code:

```
nl, _ := objlog.NewNilLogger()
	cli, err := client.NewClient(server, false, true, nl)
	if err != nil {
		log.Fatal("failed to get a client", err)
	}

	defer cli.Close()
	afd, err := cli.UserFiles()
	if err != nil {
		log.Println("Failed to get user files", err)
		return
	}

```

### What happens?

It says that i am not an admin, NOT that I am not logged in.

### What were you expecting to happen?

Complain that i am not logged in

### What versions of software are you using?

5.0.5

**Comment by john-floren-gravwell** [comment]
You got an ErrNotAdmin by calling `UserFiles`? I'd expect it from `AllUserFiles` but not `UserFiles`...

**Comment by kris-watts-gravwell** [comment]
thats the test code, you can check it

**Comment by john-floren-gravwell** [comment]
The error code I see is "Not logged in", because UserFiles calls getStaticURL which calls methodStaticURL which does this first of all:

```
	if c.state != STATE_AUTHED {
		return ErrNoLogin
	}
```

However, `AllUserFiles` looks like this:

```
	if !c.userDetails.Admin {
		err = ErrNotAdmin
	} else {
		c.SetAdminMode()
		if err = c.getStaticURL(userFilesUrl(), &ufds); err != nil {
			ufds = nil
```

and would therefore holler at you about not being admin if you haven't done the Login/Sync dance

**Comment by kris-watts-gravwell** [comment]
might be AllUserFiles then, if its just that API we can do a small fix and move on.

**Comment by john-floren-gravwell** [comment]
Revisiting this: I can make AllUserFiles check if you're logged in by adding that check on c.state I pasted earlier. That will give you the desired error message.

I thought that just eliminating the admin check would solve the problem, since getStaticURL will throw an error if you're not logged in, but the problem is that *any* user is allowed to set `?admin=true` and the API just silently ignores it if they're not an admin--so if we do want to throw an error when a non-admin calls the function, we need to check it ourselves.

Options:

* Throw an explicit check for c.state into AllUserFiles. There are surely other functions which would need a similar check, but the only way to find out is by manually looking at each one.
* Eliminate the check on c.userDetails.Admin and accept that if a non-admin user calls AllUserFiles, they're just going to get their own files and no error.

**Comment by kris-watts-gravwell** [comment]
i like option 2
