### ISSUE TITLE
CLIENT: client reports incorrect UID for logged in user

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#474]
### What are the steps to reproduce this issue?

Run this code:
```
nl, _ := objlog.NewNilLogger()
	cli, err := client.NewClient(server, false, true, nl)
	if err != nil {
		log.Fatal("failed to get a client", err)
	} else if err = cli.Login(user, password); err != nil {
		log.Fatal("login failed", err)
	}
        uid := cli.MyUID()
	fmt.Println("your uid", uid)

```

### What happens?

it says my UID is zero

### What were you expecting to happen?

show my correct UID

### What versions of software are you using?

5.0.5

**Comment by john-floren-gravwell** [comment]
Officially you're supposed to call Sync() immediately after Login.

This has been in the code forever, I assume so automated stuff that never needs to check its own UID can operate with a minimal number of HTTP requests (since figuring out your UID requires a round-trip).

We can just merge Sync into Login if we're ok with it.

**Comment by kris-watts-gravwell** [comment]
yeah, just call sync on successful login IMHO
