### ISSUE TITLE
Support more complicated json keys in preprocessors

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#558]
## Why should we add this feature? (Business justification? What problem is the feature trying to solve?)

If a json key has dots, quotes, or other monkey business our current key specifications for jsonextract, jsontimeextract, etc.. won't support it.

## How does this feature address the above problem?

Consider this blob:
```
{
  "foo": {
    "bar.baz": "stuff"
  }
}
```

We will struggle to get at the key `foo."bar.baz"`

## Any other comments?

this implementation needs to match the internal one for the json search module.

**Comment by david-fritz-gravwell** [comment]
Some fields support comma separated lists of JSON keys, which is incompatible with how gcfg removes quotes and treats backticks. For example, you cannot specify:

```
Extractions: foo.bar,`foo."bar.baz"`
```

So I propose we do the following:

1. Deprecate "Extractions" in the `jsonextract` preprocessor, in favor of "Extraction" (singular), which can be specified multiple times.
2. Deprecate "Additional-Fields` in the `jsonarraysplit` preprocessor, in favor of "Additional-Field" (singular), which can be specified multiple times.

One odd side effect of this is that in order to extract a top level key of "foo.bar" (one key with a dot in it), you'll have to wrap those double quotes in backticks:

```
Extraction=`"foo.bar"`
```

The real problem lies with the `jsonfilter` preprocessor, which has a "Field-Filter" field, which supports multiple specifications, but also contains a comma separated field of a file to compare against. For the same reason above, we can't pack raw strings into that field. 

Are there thoughts on how to split that up?

**Comment by david-fritz-gravwell** [comment]
@kris-watts-gravwell

**Comment by kris-watts-gravwell** [comment]
merged
